### ISSUE TITLE
Use // for one-line comments and /* */ for multi-line comments

### ISSUE THREAD

**Issue by timleg002** [Electrux/feral#9]
I think the # is abolishing all existing standards in other languages, where all comments are declared by // and /* */.

**Comment by Chirag-Khandelwal** [comment]
Well, that's not exactly true 🤔Most interpreted languages actually use `#` as comment symbol for single line comments. Plus, it is useful for having [shebangs](https://en.wikipedia.org/wiki/Shebang_(Unix)) in the source code.
Thanks a lot for the suggestion though 😁

**Comment by timleg002** [comment]
I don't think why you must be like every interpreted language ever.

**Comment by vitkarpov** [comment]
> I think the # is abolishing all existing standards in other languages

Python: Hold my beer!

**Comment by Chirag-Khandelwal** [comment]
@timleg002 
It's not just about being like every other programming language. Shebang is the main reason why I opted for this style. 😁
@vitkarpov haha true 😂

**Comment by timleg002** [comment]
Don't know about you, but I'm a fan of keeping languages clear. Also I really hate Python, so I thought this language was worth checking out

**Comment by Chirag-Khandelwal** [comment]
I dislike python syntax as well. But for comments, it's just a norm in interpreted languages (one that I don't mind), plus I'd really like to maintain compatibility with the `shebangs`, for which I can't forfeit this syntax.
I do hope that you still enjoy the language, however, changing comments from `#` to `//` not only provides no real benefit, but also bereaves the language of a rather useful functionality - `shebangs`.

**Comment by Electrux** [comment]
Closing.
